# Generated by Django 5.2.17 on 2026-08-13 18:10

import datetime
import django.core.validators
import django.db.models.deletion
import termine.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Terminart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Bezeichnung")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=140,
                        unique=True,
                        verbose_name="URL-Kürzel",
                    ),
                ),
                (
                    "dauer_minuten",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(600),
                        ],
                        verbose_name="Dauer (Minuten)",
                    ),
                ),
                (
                    "puffer_minuten",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Freie Zeit nach dem Termin, bevor der nächste Slot beginnt.",
                        verbose_name="Puffer danach (Minuten)",
                    ),
                ),
                (
                    "beschreibung",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "ort",
                    models.CharField(
                        blank=True,
                        help_text="Erscheint in der Bestätigungsmail und im Kalendereintrag.",
                        max_length=200,
                        verbose_name="Ort",
                    ),
                ),
                (
                    "farbe",
                    models.CharField(
                        default="#2f6f4e",
                        help_text="Hex-Farbe für die Darstellung im Backend, z. B. #2f6f4e",
                        max_length=7,
                        verbose_name="Farbe",
                    ),
                ),
                (
                    "fuehrerscheinklasse_abfragen",
                    models.BooleanField(
                        default=True,
                        help_text="Blendet im Buchungsformular die Auswahl der Führerscheinklasse ein.",
                        verbose_name="Führerscheinklasse abfragen",
                    ),
                ),
                ("aktiv", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "reihenfolge",
                    models.IntegerField(default=0, verbose_name="Reihenfolge"),
                ),
            ],
            options={
                "verbose_name": "Terminart",
                "verbose_name_plural": "Terminarten",
                "ordering": ("reihenfolge", "name"),
            },
        ),
        migrations.CreateModel(
            name="Fahrlehrer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=140,
                        unique=True,
                        verbose_name="URL-Kürzel",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Hierhin gehen die Benachrichtigungen über neue Buchungen.",
                        max_length=254,
                        verbose_name="E-Mail",
                    ),
                ),
                (
                    "telefon",
                    models.CharField(blank=True, max_length=40, verbose_name="Telefon"),
                ),
                (
                    "beschreibung",
                    models.TextField(
                        blank=True,
                        help_text="Wird auf der öffentlichen Buchungsseite angezeigt.",
                        verbose_name="Beschreibung",
                    ),
                ),
                (
                    "bundesland",
                    models.CharField(
                        choices=[
                            ("BW", "Baden-Württemberg"),
                            ("BY", "Bayern"),
                            ("BE", "Berlin"),
                            ("BB", "Brandenburg"),
                            ("HB", "Bremen"),
                            ("HH", "Hamburg"),
                            ("HE", "Hessen"),
                            ("MV", "Mecklenburg-Vorpommern"),
                            ("NI", "Niedersachsen"),
                            ("NW", "Nordrhein-Westfalen"),
                            ("RP", "Rheinland-Pfalz"),
                            ("SL", "Saarland"),
                            ("SN", "Sachsen"),
                            ("ST", "Sachsen-Anhalt"),
                            ("SH", "Schleswig-Holstein"),
                            ("TH", "Thüringen"),
                        ],
                        default="BW",
                        help_text="Bestimmt, welche gesetzlichen Feiertage bei der automatischen Terminplanung übersprungen werden.",
                        max_length=2,
                        verbose_name="Bundesland",
                    ),
                ),
                (
                    "vorlauf_stunden",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="Termine, die früher als dieser Vorlauf beginnen, sind nicht mehr buchbar.",
                        verbose_name="Mindest-Vorlauf (Stunden)",
                    ),
                ),
                (
                    "horizont_wochen",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="Wie viele Wochen im Voraus aus den Rhythmus-Regeln Termine erzeugt und zur Buchung angeboten werden.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(52),
                        ],
                        verbose_name="Planungshorizont (Wochen)",
                    ),
                ),
                (
                    "feed_token",
                    models.CharField(
                        default=termine.models.neuer_token,
                        help_text="Geheimer Teil der Kalender-Abo-URL. Beim Zurücksetzen wird das alte Abo ungültig.",
                        max_length=64,
                        unique=True,
                        verbose_name="Feed-Token",
                    ),
                ),
                ("aktiv", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "reihenfolge",
                    models.IntegerField(default=0, verbose_name="Reihenfolge"),
                ),
                (
                    "benutzer",
                    models.OneToOneField(
                        blank=True,
                        help_text="Optional. Verknüpft den Fahrlehrer mit einem Login für die Tagesplanung.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fahrlehrer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Login-Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fahrlehrer",
                "verbose_name_plural": "Fahrlehrer",
                "ordering": ("reihenfolge", "name"),
            },
        ),
        migrations.CreateModel(
            name="RhythmusRegel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bezeichnung",
                    models.CharField(
                        blank=True,
                        help_text="Nur zur Orientierung im Backend.",
                        max_length=120,
                        verbose_name="Bezeichnung",
                    ),
                ),
                (
                    "wochentage",
                    models.JSONField(
                        default=list,
                        help_text="Liste von Wochentagen (0 = Montag … 6 = Sonntag).",
                        verbose_name="Wochentage",
                    ),
                ),
                (
                    "beginn",
                    models.TimeField(default=datetime.time(9, 0), verbose_name="Von"),
                ),
                (
                    "ende",
                    models.TimeField(default=datetime.time(12, 0), verbose_name="Bis"),
                ),
                (
                    "intervall_wochen",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="1 = jede Woche, 2 = jede zweite Woche, usw.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ],
                        verbose_name="Rhythmus",
                    ),
                ),
                (
                    "referenzwoche",
                    models.DateField(
                        default=datetime.date(2024, 1, 1),
                        help_text="Nur bei mehrwöchigem Rhythmus relevant: Die Woche dieses Datums ist eine Woche, in der die Regel greift.",
                        verbose_name="Referenzdatum",
                    ),
                ),
                (
                    "gueltig_ab",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Gültig ab"
                    ),
                ),
                (
                    "gueltig_bis",
                    models.DateField(
                        blank=True,
                        help_text="Leer lassen für unbegrenzt.",
                        null=True,
                        verbose_name="Gültig bis",
                    ),
                ),
                (
                    "feiertage_auslassen",
                    models.BooleanField(
                        default=True,
                        help_text="Überspringt gesetzliche Feiertage im Bundesland des Fahrlehrers.",
                        verbose_name="Feiertage auslassen",
                    ),
                ),
                ("aktiv", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "fahrlehrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regeln",
                        to="termine.fahrlehrer",
                        verbose_name="Fahrlehrer",
                    ),
                ),
                (
                    "terminart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regeln",
                        to="termine.terminart",
                        verbose_name="Terminart",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rhythmus-Regel",
                "verbose_name_plural": "Rhythmus-Regeln",
                "ordering": ("fahrlehrer", "beginn"),
            },
        ),
        migrations.CreateModel(
            name="Termin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beginn", models.DateTimeField(db_index=True, verbose_name="Beginn")),
                ("ende", models.DateTimeField(verbose_name="Ende")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("frei", "Frei"),
                            ("reserviert", "Reserviert (wartet auf Bestätigung)"),
                            ("gebucht", "Gebucht"),
                        ],
                        db_index=True,
                        default="frei",
                        max_length=12,
                        verbose_name="Status",
                    ),
                ),
                (
                    "herkunft",
                    models.CharField(
                        choices=[
                            ("manuell", "Manuell angelegt"),
                            ("regel", "Aus Rhythmus-Regel"),
                        ],
                        default="manuell",
                        max_length=10,
                        verbose_name="Herkunft",
                    ),
                ),
                (
                    "notiz",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Interne Notiz"
                    ),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                ("geaendert_am", models.DateTimeField(auto_now=True)),
                (
                    "fahrlehrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="termine",
                        to="termine.fahrlehrer",
                        verbose_name="Fahrlehrer",
                    ),
                ),
                (
                    "regel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="termine",
                        to="termine.rhythmusregel",
                        verbose_name="Erzeugt durch Regel",
                    ),
                ),
                (
                    "terminart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="termine",
                        to="termine.terminart",
                        verbose_name="Terminart",
                    ),
                ),
            ],
            options={
                "verbose_name": "Termin",
                "verbose_name_plural": "Termine",
                "ordering": ("beginn",),
            },
        ),
        migrations.CreateModel(
            name="Sperrzeit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beginn", models.DateTimeField(verbose_name="Beginn")),
                ("ende", models.DateTimeField(verbose_name="Ende")),
                (
                    "grund",
                    models.CharField(blank=True, max_length=200, verbose_name="Grund"),
                ),
                (
                    "fahrlehrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sperrzeiten",
                        to="termine.fahrlehrer",
                        verbose_name="Fahrlehrer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sperrzeit",
                "verbose_name_plural": "Sperrzeiten",
                "ordering": ("-beginn",),
                "indexes": [
                    models.Index(
                        fields=["fahrlehrer", "beginn", "ende"],
                        name="termine_spe_fahrleh_2afcd6_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Buchung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referenz",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Referenz",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=termine.models.neuer_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="Zugriffs-Token",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="E-Mail")),
                (
                    "telefon",
                    models.CharField(blank=True, max_length=40, verbose_name="Telefon"),
                ),
                (
                    "fuehrerscheinklasse",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AM", "AM – Roller / Kleinkraftrad"),
                            ("A1", "A1 – Leichtkraftrad"),
                            ("A2", "A2 – Motorrad (mittel)"),
                            ("A", "A – Motorrad (unbeschränkt)"),
                            ("B", "B – PKW"),
                            ("B197", "B197 – PKW (Automatik-Regelung)"),
                            ("B96", "B96 – PKW mit Anhänger"),
                            ("BE", "BE – PKW mit Anhänger"),
                            ("C1", "C1 – LKW bis 7,5 t"),
                            ("C", "C – LKW"),
                            ("CE", "CE – LKW mit Anhänger"),
                            ("D1", "D1 – Kleinbus"),
                            ("D", "D – Bus"),
                            ("L", "L – Land-/Forstwirtschaft"),
                            ("T", "T – Zugmaschine"),
                            ("MOFA", "Mofa-Prüfbescheinigung"),
                            ("SONST", "Andere / weiß ich noch nicht"),
                        ],
                        max_length=8,
                        verbose_name="Führerscheinklasse",
                    ),
                ),
                ("nachricht", models.TextField(blank=True, verbose_name="Nachricht")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("offen", "Offen (E-Mail-Bestätigung ausstehend)"),
                            ("bestaetigt", "Bestätigt"),
                            ("storniert", "Storniert"),
                            ("verfallen", "Verfallen (nicht bestätigt)"),
                        ],
                        db_index=True,
                        default="offen",
                        max_length=12,
                        verbose_name="Status",
                    ),
                ),
                (
                    "reserviert_bis",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reserviert bis"
                    ),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                ("bestaetigt_am", models.DateTimeField(blank=True, null=True)),
                ("storniert_am", models.DateTimeField(blank=True, null=True)),
                (
                    "storniert_von",
                    models.CharField(
                        blank=True,
                        help_text="kunde oder fahrschule",
                        max_length=20,
                        verbose_name="Storniert von",
                    ),
                ),
                ("erinnerung_am", models.DateTimeField(blank=True, null=True)),
                (
                    "einwilligung_am",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Datenschutz-Einwilligung"
                    ),
                ),
                ("anonymisiert_am", models.DateTimeField(blank=True, null=True)),
                (
                    "termin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="buchungen",
                        to="termine.termin",
                        verbose_name="Termin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buchung",
                "verbose_name_plural": "Buchungen",
                "ordering": ("-erstellt_am",),
                "indexes": [
                    models.Index(
                        fields=["status", "reserviert_bis"],
                        name="termine_buc_status_d89327_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["offen", "bestaetigt"])),
                        fields=("termin",),
                        name="nur_eine_aktive_buchung_pro_termin",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="termin",
            index=models.Index(
                fields=["fahrlehrer", "beginn", "status"],
                name="termine_ter_fahrleh_3d88ec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="termin",
            index=models.Index(
                fields=["status", "beginn"], name="termine_ter_status_c75ae5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="termin",
            constraint=models.UniqueConstraint(
                fields=("fahrlehrer", "beginn"), name="termin_eindeutig_pro_fahrlehrer"
            ),
        ),
        migrations.AddConstraint(
            model_name="termin",
            constraint=models.CheckConstraint(
                condition=models.Q(("ende__gt", models.F("beginn"))),
                name="termin_ende_nach_beginn",
            ),
        ),
    ]
