# Generated by Django 5.2.17 on 2026-08-14 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("termine", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rhythmusregel",
            name="gueltig_ab",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="Gültig ab"
            ),
        ),
        migrations.AlterField(
            model_name="termin",
            name="status",
            field=models.CharField(
                choices=[
                    ("frei", "Frei"),
                    ("reserviert", "Reserviert (wartet auf Bestätigung)"),
                    ("gebucht", "Gebucht"),
                    ("entfallen", "Entfallen (nicht mehr im Angebot)"),
                ],
                db_index=True,
                default="frei",
                max_length=12,
                verbose_name="Status",
            ),
        ),
        migrations.AddConstraint(
            model_name="sperrzeit",
            constraint=models.CheckConstraint(
                condition=models.Q(("ende__gt", models.F("beginn"))),
                name="sperrzeit_ende_nach_beginn",
            ),
        ),
    ]
