# Generated by Django 5.2.17 on 2026-08-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0002_alter_rhythmusregel_gueltig_ab_alter_termin_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fahrlehrer',
            name='fsm_id',
            field=models.CharField(blank=True, help_text='Optionale ID des Fahrlehrers im Fahrschulmanager für automatische Synchronisation.', max_length=64, verbose_name='FSM-Fahrlehrer-ID'),
        ),
        migrations.AddField(
            model_name='fahrlehrer',
            name='fsm_sync_aktiv',
            field=models.BooleanField(default=True, help_text='Termine und Belegungszeiten automatisch mit dem Fahrschulmanager synchronisieren.', verbose_name='FSM-Sync aktiv'),
        ),
        migrations.AddField(
            model_name='sperrzeit',
            name='fsm_id',
            field=models.CharField(blank=True, help_text='Optionale FSM-Termin-ID, wenn die Sperrzeit aus dem Fahrschulmanager stammt.', max_length=64, verbose_name='FSM-ID'),
        ),
        migrations.AddField(
            model_name='termin',
            name='fsm_termin_id',
            field=models.CharField(blank=True, help_text='ID des synchronisierten Termins im Fahrschulmanager.', max_length=64, verbose_name='FSM-Termin-ID'),
        ),
    ]
