# Generated by Django 5.2.17 on 2026-08-15 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0003_fahrlehrer_fsm_id_fahrlehrer_fsm_sync_aktiv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FahrschulEinstellungen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorlauf_stunden', models.PositiveIntegerField(default=24, help_text='Termine, die früher als dieser Vorlauf beginnen, sind nicht mehr buchbar.', verbose_name='Mindest-Vorlauf (Stunden)')),
                ('horizont_wochen', models.PositiveIntegerField(default=4, help_text='Wie viele Wochen im Voraus aus den Rhythmus-Regeln Termine erzeugt und angeboten werden.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)], verbose_name='Planungshorizont (Wochen)')),
            ],
            options={
                'verbose_name': 'Fahrschul-Einstellungen',
                'verbose_name_plural': 'Fahrschul-Einstellungen',
            },
        ),
    ]
