# Generated by Django 5.2.17 on 2026-08-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0004_fahrschuleinstellungen'),
    ]

    operations = [
        migrations.AddField(
            model_name='buchung',
            name='email_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Pseudonymisierter Hash für Historien-Matching auch nach Datenlöschung', max_length=64, verbose_name='E-Mail-Hash'),
        ),
    ]
