# Generated by Django 5.2.17 on 2026-08-15 19:09

import datetime

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0005_buchung_email_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rhythmusregel',
            name='beginn',
            field=models.TimeField(default=datetime.time(15, 30), verbose_name='Von'),
        ),
        migrations.AlterField(
            model_name='rhythmusregel',
            name='ende',
            field=models.TimeField(default=datetime.time(17, 0), verbose_name='Bis'),
        ),
        migrations.AlterField(
            model_name='terminart',
            name='dauer_minuten',
            field=models.PositiveIntegerField(default=90, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(600)], verbose_name='Dauer (Minuten)'),
        ),
    ]
