# Generated by Django 5.2.17 on 2026-08-15 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0006_alter_rhythmusregel_beginn_alter_rhythmusregel_ende_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fahrschuleinstellungen',
            name='bundesland',
            field=models.CharField(choices=[('BW', 'Baden-Württemberg'), ('BY', 'Bayern'), ('BE', 'Berlin'), ('BB', 'Brandenburg'), ('HB', 'Bremen'), ('HH', 'Hamburg'), ('HE', 'Hessen'), ('MV', 'Mecklenburg-Vorpommern'), ('NI', 'Niedersachsen'), ('NW', 'Nordrhein-Westfalen'), ('RP', 'Rheinland-Pfalz'), ('SL', 'Saarland'), ('SN', 'Sachsen'), ('ST', 'Sachsen-Anhalt'), ('SH', 'Schleswig-Holstein'), ('TH', 'Thüringen')], default='BE', help_text='Bestimmt die gesetzlichen Feiertage der Fahrschule (z. B. Berlin).', max_length=2, verbose_name='Standard-Bundesland'),
        ),
        migrations.AlterField(
            model_name='fahrlehrer',
            name='benutzer',
            field=models.OneToOneField(blank=True, help_text='Optional: Verbindet diesen Fahrlehrer mit einem Login-Konto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fahrlehrer', to=settings.AUTH_USER_MODEL, verbose_name='Benutzerkonto'),
        ),
        migrations.AlterField(
            model_name='fahrlehrer',
            name='bundesland',
            field=models.CharField(choices=[('BW', 'Baden-Württemberg'), ('BY', 'Bayern'), ('BE', 'Berlin'), ('BB', 'Brandenburg'), ('HB', 'Bremen'), ('HH', 'Hamburg'), ('HE', 'Hessen'), ('MV', 'Mecklenburg-Vorpommern'), ('NI', 'Niedersachsen'), ('NW', 'Nordrhein-Westfalen'), ('RP', 'Rheinland-Pfalz'), ('SL', 'Saarland'), ('SN', 'Sachsen'), ('ST', 'Sachsen-Anhalt'), ('SH', 'Schleswig-Holstein'), ('TH', 'Thüringen')], default='BE', help_text='Bestimmt, welche gesetzlichen Feiertage bei der automatischen Terminplanung übersprungen werden.', max_length=2, verbose_name='Bundesland'),
        ),
        migrations.AlterField(
            model_name='fahrlehrer',
            name='slug',
            field=models.SlugField(blank=True, help_text='Wird für die persönliche Buchungsseite verwendet.', max_length=140, unique=True, verbose_name='URL-Kürzel'),
        ),
    ]
