# Generated by Django 5.2.17 on 2026-08-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0007_fahrschuleinstellungen_bundesland_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fahrschuleinstellungen',
            name='aktive_fuehrerscheinklassen',
            field=models.JSONField(blank=True, default=list, help_text='Welche Führerscheinklassen die Fahrschule anbietet. Leer = alle Klassen stehen zur Auswahl.', verbose_name='Verfügbare Führerscheinklassen'),
        ),
    ]
