# Generated by Django 5.2.17 on 2026-08-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0008_fahrschuleinstellungen_aktive_fuehrerscheinklassen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuehrerscheinklasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='z. B. B, B197, A, C1E', max_length=16, unique=True, verbose_name='Kürzel / Code')),
                ('name', models.CharField(help_text='z. B. PKW, PKW Automatik-Regelung', max_length=120, verbose_name='Bezeichnung')),
                ('aktiv', models.BooleanField(default=True, help_text='Inaktive Klassen werden Kunden nicht angeboten.', verbose_name='Verfügbar / Aktiv')),
                ('reihenfolge', models.IntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Führerscheinklasse',
                'verbose_name_plural': 'Führerscheinklassen',
                'ordering': ('reihenfolge', 'code'),
            },
        ),
        migrations.AlterField(
            model_name='buchung',
            name='fuehrerscheinklasse',
            field=models.CharField(blank=True, max_length=32, verbose_name='Führerscheinklasse'),
        ),
    ]
