# Generated by Django 5.2.17 on 2026-08-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0009_fuehrerscheinklasse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sperrzeit',
            name='fsm_id',
            field=models.TextField(blank=True, help_text='Optionale FSM-Termin-ID(s), wenn die Sperrzeit mit dem Fahrschulmanager verknüpft ist.', verbose_name='FSM-ID'),
        ),
    ]
