# Generated by Django 5.2.17 on 2026-08-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0010_alter_sperrzeit_fsm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sperrzeit',
            name='herkunft',
            field=models.CharField(choices=[('manuell', 'Manuell'), ('fsm', 'FSM-Import')], default='manuell', max_length=20, verbose_name='Herkunft'),
        ),
    ]
