# Generated by Django 5.2.17 on 2026-08-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0011_sperrzeit_herkunft'),
    ]

    operations = [
        migrations.AddField(
            model_name='sperrzeit',
            name='typ',
            field=models.CharField(choices=[('sonstige', 'Sonstige Tätigkeit / Urlaub (Arbeitszeit)'), ('privat', 'Privat (keine Arbeitszeit)')], default='sonstige', max_length=20, verbose_name='Art der Sperrzeit'),
        ),
    ]
