# Generated by Django 5.2.17 on 2026-08-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0012_sperrzeit_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='fahrschuleinstellungen',
            name='fsm_theorie_blockiert_beratung',
            field=models.BooleanField(default=True, help_text='Wenn ein Fahrlehrer Theorieunterricht (FSM-Terminart PT / Theorie) hat, werden in dieser Zeit für alle Fahrlehrer keine Beratungen angeboten (gemeinsamer Raum).', verbose_name='Theorieunterricht blockiert Beratungen'),
        ),
    ]
