# Generated by Django 5.2.17 on 2026-08-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0013_fahrschuleinstellungen_fsm_theorie_blockiert_beratung'),
    ]

    operations = [
        migrations.AddField(
            model_name='fahrschuleinstellungen',
            name='fsm_sync_intervall_minuten',
            field=models.PositiveIntegerField(choices=[(15, 'Alle 15 Minuten (Standard)'), (30, 'Alle 30 Minuten'), (60, 'Stündlich (60 Minuten)'), (120, 'Alle 2 Stunden (120 Minuten)'), (0, 'Deaktiviert (nur manueller Sync)')], default=15, help_text='Wie oft die Belegungszeiten (Sperren) im Hintergrund automatisch mit dem Fahrschulmanager abgeglichen werden.', verbose_name='FSM Sync-Intervall'),
        ),
    ]
