# Generated by Django 5.2.17 on 2026-08-15 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0014_fahrschuleinstellungen_fsm_sync_intervall_minuten'),
    ]

    operations = [
        migrations.AddField(
            model_name='rhythmusregel',
            name='grund',
            field=models.CharField(blank=True, help_text='z. B. Kinder aus Kita abholen, Pause, Arzt', max_length=200, verbose_name='Grund / Notiz'),
        ),
        migrations.AddField(
            model_name='rhythmusregel',
            name='regel_art',
            field=models.CharField(choices=[('angebot', 'Beratungstermine anbieten'), ('sperre', 'Sperrzeit / Blocker')], default='angebot', max_length=10, verbose_name='Art der Regel'),
        ),
        migrations.AddField(
            model_name='rhythmusregel',
            name='sperrzeit_typ',
            field=models.CharField(blank=True, choices=[('sonstige', 'Sonstige Tätigkeit / Urlaub (Arbeitszeit)'), ('privat', 'Privat (keine Arbeitszeit)')], default='privat', help_text='„Privat“ blockiert den Kalender, zählt aber in FSM nicht als Arbeitszeit.', max_length=10, verbose_name='Sperrzeit-Typ'),
        ),
        migrations.AddField(
            model_name='sperrzeit',
            name='regel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generierte_sperrzeiten', to='termine.rhythmusregel', verbose_name='Erzeugt aus Regel'),
        ),
        migrations.AlterField(
            model_name='rhythmusregel',
            name='terminart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regeln', to='termine.terminart', verbose_name='Terminart'),
        ),
    ]
