# Generated by Django 5.2.17 on 2026-08-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0015_rhythmusregel_grund_rhythmusregel_regel_art_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fahrschuleinstellungen',
            name='email_from',
            field=models.CharField(blank=True, help_text='z. B. Fahrschule Schaltwerk <termine@fahrschule-schaltwerk.de> oder info@meine-fahrschule.de', max_length=255, verbose_name='Standard-Absenderadresse'),
        ),
        migrations.AddField(
            model_name='fahrschuleinstellungen',
            name='email_host',
            field=models.CharField(blank=True, help_text='z. B. smtp.strato.de, mail.meine-fahrschule.de oder smtp.gmail.com. Leer = Fallback auf .env', max_length=255, verbose_name='SMTP-Server (Host)'),
        ),
        migrations.AddField(
            model_name='fahrschuleinstellungen',
            name='email_password',
            field=models.CharField(blank=True, help_text='Das Passwort Ihres E-Mail-Postfachs / App-Passwort.', max_length=255, verbose_name='SMTP-Passwort'),
        ),
        migrations.AddField(
            model_name='fahrschuleinstellungen',
            name='email_port',
            field=models.PositiveIntegerField(default=587, help_text='Standard: 587 (STARTTLS) oder 465 (SSL/TLS).', verbose_name='SMTP-Port'),
        ),
        migrations.AddField(
            model_name='fahrschuleinstellungen',
            name='email_use_ssl',
            field=models.BooleanField(default=False, help_text='Empfohlen für Port 465 (nicht zusammen mit STARTTLS verwenden).', verbose_name='SSL/TLS aktivieren'),
        ),
        migrations.AddField(
            model_name='fahrschuleinstellungen',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='Empfohlen für Port 587.', verbose_name='STARTTLS aktivieren'),
        ),
        migrations.AddField(
            model_name='fahrschuleinstellungen',
            name='email_user',
            field=models.CharField(blank=True, help_text='Meist Ihre vollständige E-Mail-Adresse für das Postfach.', max_length=255, verbose_name='SMTP-Benutzername'),
        ),
    ]
