# Generated by Django 5.2.17 on 2026-08-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0016_fahrschuleinstellungen_email_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fahrschuleinstellungen',
            name='erinnerung_stunden_vorher',
            field=models.PositiveIntegerField(default=24, help_text='Wie viele Stunden vor dem Beratungstermin eine automatische Erinnerungs-E-Mail an den Kunden gesendet wird (z. B. 24 für einen Tag vorher, 0 = deaktiviert).', verbose_name='Erinnerung vor Termin (Stunden)'),
        ),
        migrations.AlterField(
            model_name='fahrschuleinstellungen',
            name='email_host',
            field=models.CharField(blank=True, help_text='z. B. smtp.strato.de, mail.meine-fahrschule.de oder smtp.gmail.com.', max_length=255, verbose_name='SMTP-Server (Host)'),
        ),
    ]
