# Generated by Django 5.2.17 on 2026-08-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0017_fahrschuleinstellungen_erinnerung_stunden_vorher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fahrschuleinstellungen',
            name='erinnerung_stunden_vorher',
            field=models.PositiveIntegerField(blank=True, default=24, help_text='Wie viele Stunden vor dem Beratungstermin eine automatische Erinnerungs-E-Mail an den Kunden gesendet wird (z. B. 24 für einen Tag vorher, 0 = deaktiviert).', verbose_name='Erinnerung vor Termin (Stunden)'),
        ),
    ]
