# Generated by Django 5.2.17 on 2026-09-04 12:08
#
# Nur der Hilfetext: Das Feld wird nirgends gelesen – der Planungshorizont
# gilt fahrschulweit (FahrschulEinstellungen). Bisher versprach der Text das
# Gegenteil. An der Tabelle ändert sich nichts.

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("termine", "0018_alter_fahrschuleinstellungen_erinnerung_stunden_vorher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fahrlehrer",
            name="horizont_wochen",
            field=models.PositiveIntegerField(
                default=4,
                help_text="Ohne Wirkung: Der Planungshorizont gilt fahrschulweit und steht unter „Einstellungen“. Dieses Feld bleibt nur bestehen, damit vorhandene Daten erhalten sind.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(52),
                ],
                verbose_name="Planungshorizont (Wochen)",
            ),
        ),
    ]
