# Generated by Django 5.2.17 on 2026-09-04 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0019_horizont_wochen_ohne_wirkung'),
    ]

    operations = [
        migrations.AddField(
            model_name='fahrschuleinstellungen',
            name='reservierung_minuten',
            field=models.PositiveIntegerField(blank=True, help_text='Wie lange Kunden Zeit haben, ihre Buchung per E-Mail-Link zu bestätigen (5 bis 1440). Leer = der Wert aus RESERVATION_MINUTES (Standard 30).', null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)], verbose_name='Bestätigungsfrist (Minuten)'),
        ),
    ]
