# Generated by Django 5.2.17 on 2026-09-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0020_fahrschuleinstellungen_reservierung_minuten'),
    ]

    operations = [
        migrations.AddField(
            model_name='buchung',
            name='verfallen_am',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verfallen am'),
        ),
    ]
