# Generated by Django 6.1.1 on 2026-09-13 10:35

from django.db import migrations, models

import termine.validators


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0021_buchung_verfallen_am'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchung',
            name='email',
            field=models.EmailField(max_length=254, validators=[termine.validators.validate_email_address], verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='buchung',
            name='telefon',
            field=models.CharField(blank=True, max_length=40, validators=[termine.validators.validate_phone_number], verbose_name='Telefon'),
        ),
    ]
