# Generated by Django 6.1.1 on 2026-09-13 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0022_alter_buchung_email_alter_buchung_telefon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Erstellt am')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warnung'), ('ERROR', 'Fehler'), ('CRITICAL', 'Kritisch')], db_index=True, default='INFO', max_length=20, verbose_name='Level')),
                ('kategorie', models.CharField(choices=[('buchung', 'Buchungen'), ('termin', 'Termine & Planung'), ('fahrlehrer', 'Fahrlehrer'), ('einstellungen', 'Einstellungen'), ('auth', 'Authentifizierung'), ('system', 'System / Worker'), ('fsm', 'FSM-Gateway')], db_index=True, default='system', max_length=30, verbose_name='Kategorie / Art')),
                ('aktion', models.CharField(db_index=True, help_text="z. B. 'buchung_erstellt', 'termin_angelegt', 'buchung_storniert'", max_length=100, verbose_name='Aktion')),
                ('titel', models.CharField(max_length=255, verbose_name='Titel')),
                ('nachricht', models.TextField(blank=True, verbose_name='Nachricht / Details')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Zusatzdaten (JSON)')),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-Adresse')),
                ('benutzer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termine_system_logs', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'System-Log',
                'verbose_name_plural': 'System-Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='termine_sys_created_aa713d_idx'), models.Index(fields=['-created_at', 'kategorie'], name='termine_sys_created_485793_idx'), models.Index(fields=['-created_at', 'level'], name='termine_sys_created_dae621_idx'), models.Index(fields=['aktion'], name='termine_sys_aktion_568e7e_idx')],
            },
        ),
    ]
