# Generated by Django 6.1.1 on 2026-09-23 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0023_systemlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='KollisionsIgnorier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.DateField(verbose_name='Datum')),
                ('beginn', models.TimeField(verbose_name='Von')),
                ('ende', models.TimeField(verbose_name='Bis')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('fahrlehrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kollisions_ignoriere', to='termine.fahrlehrer', verbose_name='Fahrlehrer')),
                ('terminart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kollisions_ignoriere', to='termine.terminart', verbose_name='Terminart')),
            ],
            options={
                'verbose_name': 'Ignorierte Kollision',
                'verbose_name_plural': 'Ignorierte Kollisionen',
                'ordering': ('tag', 'beginn'),
                'constraints': [models.UniqueConstraint(fields=('fahrlehrer', 'tag', 'beginn', 'ende', 'terminart'), name='kollisions_ignorier_eindeutig')],
            },
        ),
    ]
