# Generated by Django 6.1.1 on 2026-10-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0024_kollisionsignorier'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='manuell_entfernt',
            field=models.BooleanField(default=False, help_text='Von Hand aus dem Angebot genommen, obwohl eine Rhythmus-Regel den Zeitpunkt deckt. Der Generator legt solche Termine nicht neu an.', verbose_name='Manuell entfernt'),
        ),
    ]
